language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0
services:
  - mongodb
before_script: "sh -c 'cd spec/dummy/; bundle exec rake db:migrate RAILS_ENV=test; cd ../..' "
script: 'bundle exec rspec spec'
# after_script: 'bundle exec guard-jasmine -u http://localhost:8888/'
